Configuratron:
  use_only:
#    - tueg
    - mmidb
#    - bci_iv_2a
#    - ern
#    - erpbci
#    - sleep-edf
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: "/Users/magnus/Desktop/DTU/4. semester/Fagprojekt/BENDR/encoder.pt"
context_weights: "/Users/magnus/Desktop/DTU/4. semester/Fagprojekt/BENDR/contextualizer.pt"

datasets: !include configs/downstream_datasets.yml

